---
- name: Hardened SSH Configuration 
  template: src=sshd_config dest=/etc/ssh/sshd_config

- name: Change ownership of SSH Configuration File
  file: path=/etc/ssh/sshd_config owner=root group=root mode=0644 state=file

