---
- name: Get All Interfaces
  command: /sbin/ifconfig -a
  register: ifconfig_output

- name: Get All Services Listening on interfaces
  command: netstat -nltpu
  register: netstat_output

- debug: msg="{{ ifconfig_output.stdout }}"
- debug: msg="{{ netstat_output.stdout }}"

