---
- name: Get All Interfaces
  command: /sbin/ifconfig -a
  register: ifconfig_output

- name: Get All Services Listening on interfaces
  command: netstat -nltpu
  register: netstat_output

- name: Git something?
  git: repo=https://github.com/sullo/nikto.git dest=/opt/ 

- debug: msg="{{ ifconfig_output.stdout }}"
- debug: msg="{{ netstat_output.stdout }}"

